food_shop = [
    {'name': '**Táo**', 'icon':':apple:', 'id':'`apple`', 'price':'3000', 'description': 'Táo ngọt siêu giòn nhập khẩu từ Úc'},
    {'name': '**Lê**', 'icon':':pear:', 'id':'`pear`', 'price':'3000', 'description': 'Lê cực giòn trồng ở Sa Pa'},
    {'name': '**Cam**', 'icon':':tangerine:', 'id':'`orange`', 'price':'3000', 'description': ''},
    {'name': '**Chuối**', 'icon':':banana:', 'id':'`banana`', 'price':'3000', 'description': ''},
    {'name': '**Dưa hấu**', 'icon':':watermelon:', 'id':'`watermelon`', 'price':'3000', 'description': ''},
    {'name': '**Nho**', 'icon':':grapes:', 'id':'`grape`', 'price':'3000', 'description': ''},
    {'name': '**Dâu tây**', 'icon':':strawberry:', 'id':'`strawberry`', 'price':'3000', 'description': ''},
    {'name': '**Cherry**', 'icon':':cherries:', 'id':'`cherry`', 'price':'3000', 'description': ''},
    {'name': '**Đào**', 'icon':':peach:', 'id':'`peach`', 'price':'3000', 'description': ''},
    {'name': '**Xoài**', 'icon':':mango:', 'id':'`mango`', 'price':'3000', 'description': ''},
    {'name': '**Dứa**', 'icon':':pineapple:', 'id':'`pineapple`', 'price':'3000', 'description': ''},
    {'name': '**Dừa**', 'icon':':coconut:', 'id':'`coconut`', 'price':'3000', 'description': ''},
    {'name': '**Kiwi**', 'icon':':kiwi:', 'id':'`kiwi`', 'price':'3000', 'description': ''},
    {'name': '**Cà chua**', 'icon':':tomato:', 'id':'`tomato`', 'price':'3000', 'description': ''},
    {'name': '**Ớt xanh**', 'icon':':bell_pepper:', 'id':'`bellpepper`', 'price':'3000', 'description': ''},
    {'name': '**Dưa chuột**', 'icon':':cucumber:', 'id':'`cucumber`', 'price':'3000', 'description': ''},
    {'name': '**Ớt**', 'icon':':hot_pepper:', 'id':'`hotpepper`', 'price':'3000', 'description': ''},
    {'name': '**Ngô**', 'icon':':corn:', 'id':'`corn`', 'price':'3000', 'description': ''},
    {'name': '**Cà rốt**', 'icon':':carrot:', 'id':'`carrot`', 'price':'3000', 'description': ''},
    {'name': '**Tỏi**', 'icon':':garlic:', 'id':'`garlic`', 'price':'3000', 'description': ''},
    {'name': '**Hành củ**', 'icon':':onion:', 'id':'`onion`', 'price':'3000', 'description': ''},
    {'name': '**Khoai tây**', 'icon':':potato:', 'id':'`potato`', 'price':'3000', 'description': ''},
    {'name': '**Khoai lang**', 'icon':':sweet_potato:', 'id':'`sweetpotato`', 'price':'3000', 'description': ''},
    {'name': '**Trứng**', 'icon':':egg:', 'id':'`egg`', 'price':'3000', 'description': ''},
    {'name': '**Thịt bò**', 'icon':':cut_of_meat:', 'id':'`meat`', 'price':'3000', 'description': ''},
    {'name': '**Đùi gà**', 'icon':':poultry_leg:', 'id':'`drumstick`', 'price':'3000', 'description': ''},
    {'name': '**Hotdog**', 'icon':':hotdog:', 'id':'`hotdog`', 'price':'3000', 'description': ''},
    {'name': '**Hamburger**', 'icon':':hamburger:', 'id':'`hamburger`', 'price':'3000', 'description': ''},
    {'name': '**Khoai tây chiên**', 'icon':':fries:', 'id':'`fries`', 'price':'3000', 'description': ''},
    {'name': '**Pizza**', 'icon':':pizza:', 'id':'`pizza`', 'price':'3000', 'description': ''},
    {'name': '**Bánh kếp**', 'icon':':sandwich:', 'id':'`sandwich`', 'price':'3000', 'description': ''},
    {'name': '**Salad**', 'icon':':salad:', 'id':'`salad`', 'price':'3000', 'description': ''},
    {'name': '**Lẩu gà**', 'icon':':shallow_pan_of_food:', 'id':'`hotpot`', 'price':'3000', 'description': ''},
    {'name': '**Cơm**', 'icon':':rice:', 'id':'`rice`', 'price':'3000', 'description': ''},
    {'name': '**Sushi**', 'icon':':sushi:', 'id':'`sushi`', 'price':'3000', 'description': ''},
    {'name': '**Cơm nắm**', 'icon':':rice_ball:', 'id':'`riceball`', 'price':'3000', 'description': ''},
    {'name': '**Cơm hộp**', 'icon':':bento:', 'id':'`bento`', 'price':'3000', 'description': ''},
    {'name': '**Muối**', 'icon':':salt:', 'id':'`salt`', 'price':'3000', 'description': ''},
    {'name': '**Đá lạnh**', 'icon':':ice_cube:', 'id':'`ice`', 'price':'3000', 'description': ''},
    {'name': '**Sinh tố**', 'icon':':tropical_drink:', 'id':'`smoothie`', 'price':'3000', 'description': ''},
    {'name': '**Rượu vang**', 'icon':':wine_glass:', 'id':'`wine_glass`', 'price':'3000', 'description': ''},
    {'name': '**Chè**', 'icon':':teapot:', 'id':'`tea`', 'price':'3000', 'description': ''},
    {'name': '**Cà phê**', 'icon':':coffee:', 'id':'`coffee`', 'price':'3000', 'description': ''},
    {'name': '**Sữa**', 'icon':':milk:', 'id':'`milk`', 'price':'3000', 'description': ''},
    {'name': '**Bỏng ngô**', 'icon':':popcorn:', 'id':'`popcorn`', 'price':'3000', 'description': ''},
    {'name': '**Kem**', 'icon':':ice_cream:', 'id':'`icecream`', 'price':'3000', 'description': ''},
]